----------------SQL Server LOOPS------
------While LOOP---------------

DECLARE @count INT;
SET @count = 1;
While @count <= 10
BEGIN
	Print @count;
	SET @count = @count + 1;
END
Print 'End Of While Loop'


DECLARE @count INT;
DECLARE @TableNO INT;
SET @count = 1;
SET @TableNO = 10;
while @count <=10
BEGIN
	Print concat(@TableNo,'x', @count, '=', @TableNO * @count);
	SET @count = @count + 1;
End
Print 'End Of While Loop'


DECLARE @count INT;
DECLARE @TableNO INT;
SET @count = 1;
SET @TableNO = 10;
while @count <=10
BEGIN
	Print concat(@TableNo,'x', @count, '=', @TableNO * @count);
	SET @count = @count + 1;
	if @count =5
	break;
End
Print 'End Of While Loop'

--------NESTED WHILE LOPP
DECLARE @TableNO INT;
SET @TableNO = 2;
while @TableNO <=10
BEGIN
	DECLARE @count int =1;
	while @count <=10
	Begin
		Print concat(@TableNo,'x', @count, '=', @TableNO * @count);
		SET @count = @count + 1;
	End
SET @TableNO = @TableNO + 1;
End
Print 'End Of NESTED Loop'

--------------------------------------------------------------------------------
----------Case Statements-------------
-----Case Statement in Select Statement-----
Select *,
JOB_ROLE =
Case
	WHEN Salary > 490000 THEN 'HR'
	WHEN Salary > 400000 AND Salary <= 490000 THEN 'Snr Developer'
	WHEN Salary >=200000 AND Salary <= 400000 THEN 'Jnr Developer'
	Else 'No Role'
End
from employeeDetails

------------------------
select * from employeeDetails;

Alter Table employeeDetails
Add JOB_ROLE varchar(Max);

-----Case Statement inside Update Statement
Update employeeDetails Set JOB_ROLE =
Case
	WHEN Salary > 490000 THEN 'HR'
	WHEN Salary > 400000 AND Salary <= 490000 THEN 'Snr Developer'
	WHEN Salary >=200000 AND Salary <= 400000 THEN 'Jnr Developer'
	Else 'No Role'
End

----Case Statement inside Insert Statement
Declare @Gender char(1)
Set @Gender=1;
Insert Into employeeDetails(FirstName,LastName,Gender,Address,PhoneNumber,Salary,StartDate,JOB_ROLE)
VALUES('Muntazir','Mehdi', CASE WHEN @Gender =1 THEN 'M' else 'F' End,'Kashmir',8675964876,440000,GETDATE(),'Snr Developer');

---Case Statement in Order BY Statement
Select * from employeeDetails
ORDER BY 
CASE WHEN (Select Count(gender) from employeeDetails where Gender ='M') >=5 THEN Address
Else
FirstName
END

----------------------------------------------------------------------------------------------------------------------------------------------------------------------

---If Else Condition Statement-----------------------
DECLARE @RollNo int;
DECLARE @ENGLISH INT;
DECLARE @MATHS INT;
DECLARE @SCIENCE INT;
DECLARE @TOTAL INT;
DECLARE @PERCENTAGE INT;
---INITILIAZE VARIABLSES
SET @RollNo = 101;
SET @ENGLISH = 80;
SET @MATHS = 70;
SET @SCIENCE = 90;
SET @TOTAL = @ENGLISH+@MATHS+@SCIENCE;
SET @PERCENTAGE = @TOTAL/3;

	PRINT Concat('RollNo: ',@RollNo);
	PRINT Concat ('Total: ',@TOTAL);
	PRINT Concat('Percentage: ',@PERCENTAGE);

IF @PERCENTAGE > 80
BEGIN
	PRINT 'GRADE A';
END
ELSE IF @PERCENTAGE > 60 AND @PERCENTAGE <=80 
BEGIN
	PRINT 'GRADE B';
END
ELSE IF @PERCENTAGE > 40 AND @PERCENTAGE <= 60
BEGIN
	PRINT 'GRADE C';
END
ELSE
BEGIN
	PRINT 'FAIL';
END

-----------------------------------
SELECT * FROM employeeDetails;

IF EXISTS (SELECT Address from employeeDetails where Address ='Kashmir')
BEGIN
	PRINT 'ADDRESS EXISTS';
END
ELSE
BEGIN
	PRINT ' ADDRESS DOESNOT EXIST ';
END

-----------------------------------------------------------------------
--------Exception Handling-------
------System Defined Errors-----
------System Defined Exception the Exceptions(errors) are generated by System---

Declare @a INT;
Declare @b INT;
BEGIN TRY
	SET @a = 10;
	SET @b = @a/0;
	Print 'Line 1';
	Print 'Line 2';
	Print 'Line 3';
	Print 'Line 4';
END TRY
BEGIN CATCH
	PRINT 'Inside the Catch Block'
	Print Concat('Error_Message()=' , Error_Message());
	Print Concat('Error_Line()=' , Error_Line());
	Print Concat('Error_NUMBER()=' , Error_NUMBER());
	Print Concat('Error_SEVERITY()=' , Error_SEVERITY());
	Print Concat('ERROR_STATE()=' , ERROR_STATE());
	Print Concat('ERROR_PROCEDURE()=' , ERROR_PROCEDURE());
END CATCH

------------------------
Declare @a INT;
Declare @b INT;
BEGIN TRY
	SET @a = 10;
	Print 'Line 1';
	Print 'Line 2';
	SET @b = @a/0;
	Print 'Line 3';
	Print 'Line 4';
END TRY
BEGIN CATCH
	PRINT 'Inside the Catch Block'
	Print Concat('Error_Message()=' , Error_Message());
	Print Concat('Error_Line()=' , Error_Line());
	Print Concat('Error_NUMBER()=' , Error_NUMBER());
	Print Concat('Error_SEVERITY()=' , Error_SEVERITY());
	Print Concat('ERROR_STATE()=' , ERROR_STATE());
	Print Concat('ERROR_PROCEDURE()=' , ERROR_PROCEDURE());
END CATCH

------------------------------
Declare @a INT;
Declare @b INT;
BEGIN TRY
	SET @a = 10;
	Print 'Line 1';
	Print 'Line 2';
	SET @b = @a/5;
	Print 'Line 3';
	Print 'Line 4';
END TRY
BEGIN CATCH
	PRINT 'Inside the Catch Block'
	Print Concat('Error_Message()=' , Error_Message());
	Print Concat('Error_Line()=' , Error_Line());
	Print Concat('Error_NUMBER()=' , Error_NUMBER());
	Print Concat('Error_SEVERITY()=' , Error_SEVERITY());
	Print Concat('ERROR_STATE()=' , ERROR_STATE());
	Print Concat('ERROR_PROCEDURE()=' , ERROR_PROCEDURE());
END CATCH

-------------------------------------
---USER DEFINED ERRORS--
---THE THROW STATEMENT IN SQL RAISES AN EXCEPTION AND TRANSFERS THE CONTROL TO A CATCH BLOCK.
----SYNTAX: THROW @ERRORNUMBER, @ERRORMESSAGE, @ERRORSEVERITY
	--ERROR NO -> 50000 TO 2147483647
	--ERROR SEVERITY 
		--13-> INDICATES TRANSACTION DEADLOCK ERRORS.
		--14-> INDICATES  SECURITY RELATED ERRORS,SUCH AS PERMISSION DENIED.
		--15-> INDICATES SYNTAX ERRORS IN THE TRANSACT-SQL COMMAND.
		--16 -> INDICATED GENERAL ERRORS THAT CAN BE CORRECTED BY THE USER.


DECLARE @AGE INT;
BEGIN TRY
	SET @AGE = 60;
	PRINT 'LINE 1'
	PRINT 'LINE 2'
	IF @AGE > 40
		THROW 50000,'AGE IS GREATER THAN 40',16;
	PRINT 'LINE 3'
	PRINT 'LINE 4'
END TRY
BEGIN CATCH
	PRINT 'Inside the Catch Block'
	Print Concat('Error_Message()=' , Error_Message());
	Print Concat('Error_Line()=' , Error_Line());
	Print Concat('Error_NUMBER()=' , Error_NUMBER());
	Print Concat('Error_SEVERITY()=' , Error_SEVERITY());
	Print Concat('ERROR_STATE()=' , ERROR_STATE());
	Print Concat('ERROR_PROCEDURE()=' , ERROR_PROCEDURE());
END CATCH


------
DECLARE @AGE INT;
BEGIN TRY
	SET @AGE = 60;
	PRINT 'LINE 1'
	PRINT 'LINE 2'
	IF @AGE > 40
		RAISERROR ('AGE IS GREATER THAN 40',16,3);        ---RAISERROR CAN BE USED EVEN WITHOUT TRY CATCH
	PRINT 'LINE 3'
	PRINT 'LINE 4'
END TRY
BEGIN CATCH
	PRINT 'Inside the Catch Block'
	Print Concat('Error_Message()=' , Error_Message());
	Print Concat('Error_Line()=' , Error_Line());
	Print Concat('Error_NUMBER()=' , Error_NUMBER());
	Print Concat('Error_SEVERITY()=' , Error_SEVERITY());
	Print Concat('ERROR_STATE()=' , ERROR_STATE());
	Print Concat('ERROR_PROCEDURE()=' , ERROR_PROCEDURE());
END CATCH







